// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	repository2 "github.com/andreluizmicro/go-soccer/internal/country/domain/repository"
	"github.com/andreluizmicro/go-soccer/internal/country/infrastructure/repository"
	"github.com/andreluizmicro/go-soccer/internal/country/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateCountryUseCase(db *sql.DB) *country.CreateCountryUseCase {
	countryRepository := repository.NewCountryRepository(db)
	createCountryUseCase := country.NewCreateCountryUseCase(countryRepository)
	return createCountryUseCase
}

// wire.go:

var setCountryRepositoryDependency = wire.NewSet(repository.NewCountryRepository, wire.Bind(new(repository2.CountryRepositoryInterface), new(*repository.CountryRepository)))
